# Generated by Django 5.2 on 2026-09-18 06:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_expand_reranker_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DingTalkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用钉钉同步')),
                ('app_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Client ID / AppKey')),
                ('app_secret', models.CharField(blank=True, default='', max_length=500, verbose_name='Client Secret / AppSecret')),
                ('operator_user_id', models.CharField(blank=True, default='', help_text='企业管理后台通讯录中的 User ID，平台会自动解析为 unionId', max_length=100, verbose_name='操作人 User ID')),
                ('operator_union_id', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人 unionId 缓存')),
                ('access_token', models.CharField(blank=True, default='', max_length=500, verbose_name='accessToken 缓存')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='accessToken 过期时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '钉钉同步配置',
                'verbose_name_plural': '钉钉同步配置',
            },
        ),
        migrations.CreateModel(
            name='DingTalkSyncBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=100, verbose_name='钉钉知识库 ID')),
                ('workspace_name', models.CharField(blank=True, default='', max_length=200, verbose_name='钉钉知识库名称')),
                ('root_node_id', models.CharField(blank=True, default='', help_text='为空时同步整个知识库（使用钉钉返回的 rootNodeId）', max_length=100, verbose_name='同步根节点 ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用定时同步')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='同步间隔(分钟)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间')),
                ('last_status', models.CharField(choices=[('idle', '空闲'), ('running', '同步中'), ('success', '成功'), ('failed', '失败')], default='idle', max_length=20, verbose_name='上次同步状态')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='上次错误')),
                ('last_report', models.JSONField(blank=True, default=dict, verbose_name='上次同步报告')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '钉钉同步绑定',
                'verbose_name_plural': '钉钉同步绑定',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='外部文档 ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='外部修改时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='外部目录路径'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='外部原始链接'),
        ),
        migrations.AddField(
            model_name='document',
            name='external_workspace_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='外部知识库 ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已归档'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word文档'), ('doc', 'Word文档(旧版)'), ('xlsx', 'Excel表格'), ('xls', 'Excel表格(旧版)'), ('pptx', 'PowerPoint'), ('txt', '文本文件'), ('md', 'Markdown'), ('html', 'HTML'), ('url', '网页链接'), ('dingtalk', '钉钉文档')], max_length=10, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='网页链接'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'dingtalk'), ('external_id__isnull', False)), fields=('knowledge_base', 'document_type', 'external_id'), name='uniq_kb_dingtalk_external_id'),
        ),
        migrations.AddField(
            model_name='dingtalkconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dingtalk_configs', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='dingtalksyncbinding',
            name='knowledge_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dingtalk_binding', to='knowledge.knowledgebase', verbose_name='本地知识库'),
        ),
    ]
