# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('langgraph_integration', '0026_restore_llmconfig_table_if_missing'),
    ]

    # Portable schema operations work on the local SQLite database.
    operations = [
        migrations.AddField(
            model_name='chatsession', name='resolved_module_key',
            field=models.CharField(default='llm_chat', max_length=64, verbose_name='解析模块Key'),
        ),
        migrations.AddField(
            model_name='chatsession', name='resolved_source',
            field=models.CharField(default='legacy', max_length=32, verbose_name='LLM配置来源'),
        ),
        migrations.AddField(
            model_name='chatsession', name='resolved_bundle_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='解析配置包ID'),
        ),
        migrations.AddField(
            model_name='chatsession', name='resolved_runtime_mode',
            field=models.CharField(default='auto', max_length=16, verbose_name='运行模式'),
        ),
    ]
